db/seeds.rb

Here's the most updated version of the seed data.

Adds seed data lined with schema

---

app/controllers/carts_controller.rb
app/controllers/items_controller.rb
app/controllers/merchants_controller.rb
app/controllers/sessions_controller.rb
app/controllers/users_controller.rb
app/controllers/welcome_controller.rb
app/views/layouts/application.html.erb
config/routes.rb
spec/features/nav_bar_spec.rb

Needs more Item and Cart setup to finalize cart item count. routes/controllers/empty views completed.

User story 2

---

spec/features/users/login_spec.rb

Competes tests for user stories 10-12

Visitor new #69

---

app/models/user.rb
spec/features/items/index_spec.rb
spec/features/items/show_spec.rb
spec/models/item_spec.rb

Also all parent test data should be resolved

Fixes before :each examples and hashes out tests

---

app/controllers/application_controller.rb
app/controllers/sessions_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/views/layouts/application.html.erb
app/views/sessions/new.html.erb
app/views/users/new.html.erb
app/views/users/show.html.erb
config/routes.rb
spec/features/users/login_spec.rb
spec/features/users/logout_spec.rb

Still needs flash message for logging out

Visitor new #66

---

app/controllers/admin/admins_controller.rb
app/controllers/application_controller.rb
app/controllers/carts_controller.rb
app/controllers/merchants_controller.rb
app/controllers/sessions_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/views/layouts/application.html.erb
config/routes.rb
spec/features/nav_bar_spec.rb
spec/features/users/login_spec.rb
spec/features/users/logout_spec.rb

completes user story 6. Needed to add access restrictions to cart path.

User story 6

---

spec/features/users/show_spec.rb

Change show_spec to reflect change from user_path(user) to profile_path.

---

spec/features/users/edit_spec.rb

Pushing to combine with Ethan's edit user functionality.

User new #59

---

app/controllers/carts_controller.rb
app/models/cart.rb
app/views/carts/show.html.erb
spec/features/users/cart_spec.rb
spec/models/cart_spec.rb

Cart show1

---

app/controllers/sessions_controller.rb
spec/features/users/edit_spec.rb
spec/features/users/login_spec.rb
spec/features/users/show_spec.rb

Comments out flash message tests and unskips all

---

app/views/carts/show.html.erb
spec/features/users/cart_spec.rb

Completes User Story 22

---

app/assets/stylesheets/application.css
app/views/carts/show.html.erb

Adds styling to cart show page.

---

spec/features/users/cart_spec.rb

Adds test for quantity adjusting to zero

---

app/controllers/items_controller.rb
app/controllers/merchants_controller.rb
app/controllers/sessions_controller.rb
app/controllers/users_controller.rb
app/models/item.rb
app/models/order_item.rb
app/views/items/index.html.erb
app/views/merchants/show.html.erb
app/views/users/show.html.erb
config/routes.rb
spec/features/merchants/show_spec.rb
spec/models/item_spec.rb
spec/models/order_item_spec.rb

User stories 34,35,37. Check waffle comments. Fully tested with 1 skipped test. 100% rspec.

Eg merchant stories

---

app/controllers/merchants_controller.rb
app/models/user.rb
app/views/merchants/index.html.erb
spec/features/merchants/index_spec.rb
spec/models/user_spec.rb

Visitor new #34

---

app/controllers/dashboard/orders_controller.rb
app/views/dashboard/orders/show.html.erb
app/views/merchants/show.html.erb
config/routes.rb
spec/features/merchants/show_spec.rb

Completed the lnk_to orders page portion of story

Eg story 35 complete

---

app/controllers/dashboard/items_controller.rb
app/views/dashboard/items/index.html.erb
spec/features/dashboard_spec.rb

The links don't have any routing yet, but the card as written is complete

Completes user story 44

---

app/controllers/dashboard/items_controller.rb
app/views/dashboard/items/index.html.erb
config/routes.rb
spec/features/dashboard_spec.rb

What I did in the routes may be unfamiliar. Check docs if you're interested.

Eg story 45 46 complete

---

app/controllers/sessions_controller.rb
spec/features/users/login_spec.rb

Visitor new #67

---

spec/models/user_spec.rb

procides additional testing context and updates test name to .active_merchants

updates test to clarify purpose

---

app/controllers/dashboard/items_controller.rb
app/models/item.rb
app/views/dashboard/items/edit.html.erb
app/views/dashboard/items/index.html.erb
app/views/dashboard/items/new.html.erb
config/routes.rb
db/migrate/20190407122409_add_default_enabled_to_items.rb
db/schema.rb
spec/features/dashboard_spec.rb

Functionality only. Tests to be written. Does not break rspec other than one failure from Jeremy.

Eg user story 48

---

db/seeds.rb

Updates seeds file to destroy_all resources.

---

app/controllers/admin/merchants_controller.rb
app/controllers/sessions_controller.rb
app/models/user.rb
app/views/admin/merchants/index.html.erb
app/views/merchants/show.html.erb
config/routes.rb
spec/features/admin_spec.rb
spec/features/merchants/show_spec.rb
spec/features/users/cart_spec.rb
spec/features/users/login_spec.rb
spec/models/user_spec.rb

Completes 2 of 7 pieces of user story 36

Merchant show statistics

---

app/controllers/merchants_controller.rb
app/views/merchants/show.html.erb
spec/features/merchants/show_spec.rb

Fixes merchant dashboard orders show

---

app/controllers/dashboard/orders_controller.rb
app/models/user.rb
app/views/dashboard/orders/show.html.erb
config/routes.rb
spec/features/dashboard/orders_spec.rb
spec/features/merchants/user_story_36_part_3_through_7_spec.rb
spec/models/merchant_stats_spec.rb

completes user story 53

---

app/controllers/admin/merchants_controller.rb
app/controllers/admin/users_controller.rb
app/views/admin/merchants/show.html.erb
config/routes.rb

@JaxJafinPapau This is untested. If you could write tests for it that would be appreciated. Tests to be added (not exhaustive) : test link exists on merchant show page. test link downgrades user (test role). Test merchant items are disabled. @merchant.items[0] (enabled: false?) (no need to test all of the items)

Eg story 59

---

app/controllers/merchants_controller.rb
app/models/user.rb
app/views/merchants/show.html.erb
spec/features/admin_spec.rb
spec/features/merchants/user_story_36_part_3_through_7_spec.rb
spec/models/user_spec.rb

Adds top_user method

---

db/migrate/20190409171843_adds_default_image_to_item.rb
db/schema.rb

Creates and migrates default item image url

---

app/views/admin/merchants/index.html.erb

Adds a .order to index so that tests remain consistent

---

app/controllers/admin/merchants_controller.rb
app/controllers/admin/users_controller.rb

Adds before action to admin controllers

---

app/controllers/admin/merchants_controller.rb
app/controllers/dashboard/orders_controller.rb
app/controllers/items_controller.rb
app/models/order.rb
app/views/admin/merchants/index.html.erb
spec/features/dashboard/orders_spec.rb
spec/features/items/index_spec.rb
spec/models/order_spec.rb

Finishes User Story 31, fixes intermittent ordering errors

---

spec/features/dashboard/items_spec.rb
spec/features/dashboard_spec.rb

Adds sad path test to merchant dashboard items path

---

app/controllers/application_controller.rb

Updates login functionality to exclude merchants who are disabled

---

app/controllers/merchants_controller.rb
app/models/item.rb
app/models/user.rb
app/views/merchants/index.html.erb
spec/features/merchants/user_story_36_part_3_through_7_spec.rb
spec/features/merchants/user_story_40_spec.rb
spec/models/item_spec.rb
spec/models/merchant_stats_spec.rb

User Story 40 statistics methods with tests/views

Merch stats

---

app/assets/stylesheets/application.css
app/views/layouts/application.html.erb

adds navbar styling

---

app/controllers/carts_controller.rb
app/controllers/sessions_controller.rb
app/views/admin/merchants/show.html.erb
spec/features/users/cart_spec.rb
spec/features/users/login_spec.rb

Fixed the needed changes to a few stories.

Flash changes

---

spec/features/admin_spec.rb
spec/features/merchants/user_story_40_spec.rb

Post styling test updates to accomodate changes to css tags and context giving view text

View order test refactor

---

app/assets/stylesheets/application.css
app/views/admin/merchants/index.html.erb
app/views/admin/users/index.html.erb
app/views/carts/show.html.erb
app/views/dashboard/items/index.html.erb
app/views/merchants/show.html.erb
app/views/users/show.html.erb
app/views/welcome/index.html.erb

Finishes(?) styling

---

spec/features/admin_spec.rb
spec/features/users/show_spec.rb

refactors tests to accomodate changes to css tag

---

spec/features/admin_spec.rb

100% test coverage my lovelies

Downgrade feature test

---

app/views/layouts/application.html.erb

phew!! Fixes accidental revert of application.css

Fixes application.css revert

---

app/controllers/admin/users_controller.rb
app/models/user.rb

Fixes order to stabilize testing.

---

app/controllers/admin/orders_controller.rb
app/views/admin/admins/show.html.erb
config/routes.rb
spec/features/admin_spec.rb

adds admin ship functionality

---

db/migrate/20190410210251_add_default_to_order_items.rb
db/schema.rb
db/seeds.rb

Adds default value to orderitem fulfilled.

---

app/controllers/sessions_controller.rb
spec/features/users/login_spec.rb

if merchant disabled flash message and redirect + tests. 100% test coverage

Merchant disabled

---

app/models/item.rb
app/views/items/show.html.erb

Fixes no shipment edge case
